export const ActionType = {
  GET_USERS_INIT: 'GET_USERS_INIT',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAILURE: 'GET_USERS_FAILURE',
  CLEAR_STORE: 'CLEAR_STORE',
  SET_PAGE: 'SET_PAGE',
  GET_CURRENT_USER_INIT: 'GET_CURRENT_USER_INIT',
  GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
  GET_CURRENT_USER_FAILURE: 'GET_CURRENT_USER_FAILURE',
};
