export const ActionType = {
  GET_USERS_INIT: 'GET_USERS_INIT',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAILURE: 'GET_USERS_FAILURE',
  CLEAR_STORE: 'CLEAR_STORE',
  SET_PAGE: 'SET_PAGE',
};
